from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('info', views.Info),
    path('u10/<str:latitude>/<str:longitude>/<str:time>', views.u10),
    path('v10/<str:latitude>/<str:longitude>/<str:time>', views.v10),
    path('t2m/<str:latitude>/<str:longitude>/<str:time>', views.t2m),
    path('anor/<str:latitude>/<str:longitude>', views.anor),
    path('isor/<str:latitude>/<str:longitude>', views.isor),
    path('z/<str:latitude>/<str:longitude>/<str:time>/<str:level>', views.z),
    path('z_surface/<str:latitude>/<str:longitude>', views.z_surface),
    path('cvh/<str:latitude>/<str:longitude>', views.cvh),
    path('cl/<str:latitude>/<str:longitude>', views.cl),
    path('lsm/<str:latitude>/<str:longitude>', views.lsm),
    path('cvl/<str:latitude>/<str:longitude>', views.cvl),
    path('msl/<str:latitude>/<str:longitude>/<str:time>', views.msl),
    path('siconc/<str:latitude>/<str:longitude>/<str:time>', views.siconc),
    path('sst/<str:latitude>/<str:longitude>/<str:time>', views.sst),
    path('slor/<str:latitude>/<str:longitude>', views.slor),
    path('slt/<str:latitude>/<str:longitude>', views.slt),
    path('q/<str:latitude>/<str:longitude>/<str:time>/<str:level>', views.q),
    path('sdfor/<str:latitude>/<str:longitude>', views.sdfor),
    path('sdor/<str:latitude>/<str:longitude>', views.sdor),
    path('sp/<str:latitude>/<str:longitude>/<str:time>', views.sp),
    path('t/<str:latitude>/<str:longitude>/<str:time>/<str:level>', views.t),
    path('tisr/<str:latitude>/<str:longitude>/<str:time>', views.tisr),
    path('tcc/<str:latitude>/<str:longitude>/<str:time>', views.tcc),
    path('tvh/<str:latitude>/<str:longitude>', views.tvh),
    path('tvl/<str:latitude>/<str:longitude>', views.tvl),
    path('u/<str:latitude>/<str:longitude>/<str:time>/<str:level>', views.u),
    path('v/<str:latitude>/<str:longitude>/<str:time>/<str:level>', views.v),
    path('w/<str:latitude>/<str:longitude>/<str:time>/<str:level>', views.w),
]
